### ISSUE TITLE
Is possible simulate the Segment on localhost?

### ISSUE THREAD

**Issue by pedroSoaresll** [segmentio/docker-image#3]
On my work I use segment but debug is not a simple task, because I have to deploy the app to dev environment and test segment. 

Is there a way to test segment on localhost?

**Comment by power-f-GOD** [comment]
Were you able to do this on localhost?

**Comment by pedroSoaresll** [comment]
@power-f-GOD thank you for your question, actually, I'm don't using any more segment.io :)
